# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProtoPluginDialog

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-07
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Dennis
        email                : Dbenz@uni.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .exampleDataWindow import ExampleDataWindow
from .createGraphWindow import CreateGraphWindow
from .ogdfAnalysisWindow import OGDFAnalysisWindow
from .jobsWindow import JobsWindow
from .optionsWindow import OptionsWindow



# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'protoPluginDialog.ui'))


class ProtoPluginDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super(ProtoPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # left navigation
        self.menu_list.currentRowChanged['int'].connect(
            self.stacked_content_window.setCurrentIndex)

        # setup each content view
        self.contentWindows = [
            ExampleDataWindow(self),
            CreateGraphWindow(self),
            OGDFAnalysisWindow(self),
            JobsWindow(self),
            OptionsWindow(self),
        ]

        for contentWindow in self.contentWindows:
            contentWindow.setupWindow()

        # create example data as default
        self.menu_list.setCurrentRow(0)




